# High level configuration
output_dir: data/results
data_source: simulation
random_seed: 11
n_bootstraps: 1

# Simulation setup
n_samples: 100000
n_features: 6
distribution: beta_prime
parameter_function: |
  def parameter(X):
      # log(mu) = a0 + a1*sin(a2*x2) + a3*x3*x4
      # a0=0.3, a1=0.5, a2=2.0, a3=0.3
      z0 = (0.3
            + 0.5 * np.sin(2.0 * X[:,1])
            + 0.3 * X[:,2] * X[:,3])
      # log(v) = b0 + min(b1, b2*x2) + b3*min(b4, b5*|x3|) + b6*x6*x3
      # b0=1.5, b1=0.5, b2=0.4, b3=0.3, b4=0.8, b5=0.6, b6=0.2
      z1 = (1.5
            + np.minimum(0.5, 0.4 * X[:,1])
            + 0.3 * np.minimum(0.8, 0.6 * np.abs(X[:,2]))
            + 0.2 * X[:,5] * X[:,2])
      return np.stack([z0, z1])

# Preprocessing setup
test_size: 0.2
normalize: True

# Model setup
models:
  - intercept
  - cglm
  - gbm
  # - ngboost
  - cgbm

# Model hyperparameters
model_hyperparameters:
  cglm:
    max_iter: 2000
    tolerance: 1e-5
    step_size: 0.1
  gbm:
    n_estimators: 600
    max_depth: 4
    learning_rate: 0.05
  ngboost:
    n_estimators: 2000
    learning_rate: 0.01
    early_stopping_rounds: 50
  cgbm:
    n_estimators:
     - 500
     - 500
    max_depth: 4
    learning_rate:
      - 0.1
      - 0.1

# Model tuning
tuning: true
n_splits: 4
parallel: false
