# High level configuuration
output_dir: data/results
data_source: simulation
random_seed: 11
 
# Simulation setup
n_samples: 10000
n_features: 2
distribution: normal
parameter_function: |
  def parameter(X):
      z0 = 1.5*X[:,0]**2
      z1 = 0.1 + 0.2*(X[:,1]>0)
      return np.stack([z0,z1])

# Preprocessing setup
test_size: 0.2
normalize: True

# Model setup
models:
  - intercept
  - cglm
  - gbm
  - cgbm

# Model hyperparameters
model_hyperparameters:
  cglm:
    max_iter: 1000
    tolerance: 1e-5
    step_size: 1e-5
  gbm:
    n_estimators: 442 # 600
    max_depth: 3
    learning_rate: 0.01
  cgbm: 
    n_estimators: 
     - 487 # 600
     - 439 # 600
    max_depth: 3
    learning_rate: 0.01

# Model tuning
tuning: false
n_splits: 4
parallel: true
