# Gaussian simulated example
# High level configuuration
output_dir: data/results
data_source: simulation
random_seed: 11
 
# Simulation setup
n_samples: 100000
n_features: 8
distribution: normal
parameter_function: |
  def parameter(X):
      z0 = 0.8*X[:,0] + 0.6*X[:,1]**2 + 0.7*np.abs(X[:,2])*np.sin(X[:,1]) + 0.5*X[:,3]*X[:,4]**2
      z1 = 0.2*X[:,1] + 0.15*np.abs(X[:,0])*np.sin(X[:,1]) + 0.15*(X[:,1]>0)
      return np.stack([z0,z1])

# Preprocessing setup
test_size: 0.2
normalize: True

# Model setup
models:
  - intercept
  - cglm
  - gbm
  - cgbm

# Model hyperparameters
model_hyperparameters:
  cglm:
    max_iter: 1000
    tolerance: 1e-5
    step_size: 0.1
  gbm:
    n_estimators: 500
    max_depth: 2
    learning_rate: 0.05
  cgbm: 
    n_estimators: 
     - 500
     - 500
    max_depth: 2
    learning_rate: 0.05
  cgbm: 
    n_estimators: 
     - 500
     - 500
    max_depth: 4
    learning_rate:
      - 0.050
      - 0.025

# Model tuning
tuning: true
n_splits: 4
parallel: true
