# Data setup
data_source: simulation

# Simulation setup
n: 10000
p: 3
random_seed: 123
test_size: 0.5

# Distribution setup
distribution: gamma
parameter_function: |
  def z(X):
      z0 = X[:, 0] + 10*(X[:, 1]>0)
      z1 = 3-2*(X[:, 1]>0)
      return np.stack([z0,z1])

# Model setup
models:
- intercept
- cyc-gbm
# Hyperparameters
gbm_parameters:
  eps: 0.1
  kappa_max: 1000
  max_depth: 2
  min_samples_leaf: 10
  n_splits: 2

# Output setup
output_figures: false
copy_data: true
output_path: data/results/
figure_format:
verbose: 2
