# Data setup
data_name: normal_simulation
data_source: simulation

# Distribution setup
distribution: normal
parameter_function: |
  def z(X):
      z0 = 1 + 0.5*np.sin(X[:,0])
      z1 = 2 - 0.3*(X[:,0]>0)
      return np.stack([z0,z1])
