# Data setup
data_name: normal_simulation
data_source: simulation

# Distribution setup
distribution: normal
parameter_function: |
  def z(X):
      z0 = 1 + 0.5*X[:,1] - 0.25*X[:,2]**2
      z1 = 2 + 0.3*X[:,2]
      return np.stack([z0,z1])
