# Data setup
data_name: claim_counts
data_source: real

# Distribution setup
distribution: neg_bin
input_path: /Users/Henning/PycharmProjects/c-gbm/data/cas_data/claim_counts.csv

glm_parameters:
  eps: 1e-15
  max_iter: 10000
  tol: 0.01
gbm_parameters:
  eps: 0.1
  kappa_max: 1000
  max_depth: 3
  min_samples_leaf: 20
  n_splits: 10
