# Data setup
data_name: claim_amounts
data_source: real

# Distribution setup
distribution: neg_bin
input_path: /Users/Henning/PycharmProjects/c-gbm/data/cas_data/claim_amounts.csv

glm_parameters:
  eps: 1e-12
  max_iter: 1000000
  tol: 0.01
gbm_parameters:
  eps: 0.01
  kappa_max: 1000
  max_depth: 2
  min_samples_leaf: 20
  n_splits: 10
