# Simulation setup
n: 100000
p: 9
random_seed: 11
test_size: 0.2

# Model setup
models:
- intercept
- cyc-glm
- uni-gbm
- cyc-gbm

# Output setup
copy_data: true
output_figures: false
output_path: ../../data/results/
verbose: 2

# Config setup
sub_configs: ../../config/simulation_study/sub_configs/
