# Simulation setup
n: 100000
p: 9
random_seed: 123
test_size: 0.2

# Model setup
models:
- intercept
- cyc-glm
- uni-gbm
- cyc-gbm
# Hyperparameters
glm_parameters:
  eps: 0.00001
  max_iter: 1000
  tol: 0.001
gbm_parameters:
  eps: 0.1
  kappa_max: 1000
  max_depth: 3
  min_samples_leaf: 5
  n_splits: 2

# Output setup
output_figures: false
copy_data: true
output_path: ../../data/results/
figure_format:
verbose: 2

# Config setup
sub_configs: ../../config/simulation_run/sub_configs/
