# Simulation setup
n: 1000
p: 1
random_seed: 123
test_size: 0.2

# Model setup
models:
- intercept
#- cyc-glm
#- uni-gbm
- cyc-gbm
# Hyperparameters
glm_parameters:
  eps: 0.00001
  max_iter: 100
  tol: 0.001
gbm_parameters:
  eps: 0.1
  kappa_max: 100
  max_depth: 3
  min_samples_leaf: 5
  n_splits: 2

# Output setup
copy_data: true
output_path: ../../data/results/
figure_format:
verbose: 2

# Config setup
sub_configs: ../../config/simulation_run/sub_configs/
