# Data setup
data_name: beta_prime_simulation
data_source: simulation

# Distribution setup
distribution: beta_prime
parameter_function: |
  def z(X):
    z0 = 2 + 2*np.sin(0.2*X[:,1]) + 0.05*X[:,2]*X[:,5]
    z1 = -0.5 + 0.1*X[:,1] + np.minimum(1, 5*np.abs(X[:,2])) + 0.05*X[:,5]*X[:,2]
    return np.stack([z0,z1])

glm_parameters:
  eps: 1e-5
  max_iter: 1000
  tol: 0.01
gbm_parameters:
  eps: 0.2
  kappa_max: 100
  max_depth: 3
  min_samples_leaf: 5
  n_splits: 10