# Data setup
data_name: normal_simulation
data_source: simulation

# Distribution setup
distribution: normal
parameter_function: |
  def z(X):
      z0 = 1.5*X[:,1] + 2*X[:,3] - 0.65*X[:,2]**2 + 0.5*np.abs(X[:,3])*np.sin(0.5*X[:,2]) + 0.45*X[:,4]*X[:,5]**2
      z1 = 1 + 0.02*X[:,2] + 0.5*X[:,1]*(X[:,1]<2) + 1.8*(X[:,5]>0)
      return np.stack([z0,z1])

glm_parameters:
  eps: 1e-8
  max_iter: 10000
  tol: 0.01
gbm_parameters:
  eps: 0.1
  kappa_max: 250
  max_depth: 3
  min_samples_leaf: 5
  n_splits: 10