# Data setup
data_name: gamma_simulation
data_source: simulation

# Distribution setup
distribution: gamma
parameter_function: |
  def z(X):
    z0 = -1 + 0.5*X[:,1] - 0.25*X[:,2]**2 + 0.5*np.abs(X[:,3])*np.sin(2*X[:,3]) * 0.25*X[:,4]*X[:,5]+0.125*X[:,5]**2*X[:,6]
    z1 = 2 + 0.3*X[:,2]+0.02*np.abs(X[:,1])
    return np.stack([z0,z1])
  

glm_parameters:
  eps: 1e-5
  max_iter: 1000
  tol: 0.01
gbm_parameters:
  eps: 0.1
  kappa_max: 1000
  max_depth: 3
  min_samples_leaf: 5
  n_splits: 10