# Data setup
data_name: inverse_gaussian_simulation
data_source: simulation

# Distribution setup
distribution: inv_gauss
parameter_function: |
  def z(X):
    z0 = 0.003*X[:,1]*X[:,2]*X[:,3] + 0.3*np.abs(X[:,4])
    z1 = 1 + 0.3*(X[:,1]>0) + 0.5*X[:,2]*(X[:,5]>0)
    return np.stack([z0,z1])

glm_parameters:
  eps: 1e-6
  max_iter: 1000
  tol: 0.01
gbm_parameters:
  eps: 0.01
  kappa_max: 500
  max_depth: 3
  min_samples_leaf: 4
  n_splits: 10