# Data setup
data_name: neg_bin_simulation
data_source: simulation

# Distribution setup
distribution: neg_bin
parameter_function: |
  def z(X):
    z0 = -1 + 0.004*np.minimum(2, X[:,4])**2 + 2.2*np.minimum(0.5, X[:,1]) + np.sin(0.3*X[:,2])
    z1 = -2 + 0.3*(X[:,1] > 0) + 0.2*np.abs(X[:,2])*(X[:,5] > 0) + 0.2*X[:,3]
    return np.stack([z0,z1])

glm_parameters:
  eps: 1e-6
  max_iter: 10000
  tol: 0.01
gbm_parameters:
  eps: 0.1
  kappa_max: 100
  max_depth: 3
  min_samples_leaf: 5
  n_splits: 10