"""Tikz groupplot writer for the binned response plot.

Produces a ``.tex`` snippet that can be ``\\input``-ted directly into a LaTeX
document, matching the style of the existing ``src/figures/beta_prime_sim.tex``
in the paper repository.

Each subplot is rendered with:
- A filled grey path for the ±1 std band (drawn as a closed polygon via
  ``\\addplot fill between`` over the upper and lower ``.dat`` files).
- A thick black line for the predicted bin mean.
- Black dots (``only marks``) for the observed bin averages.
"""

from __future__ import annotations

from pathlib import Path


def _rel(dat_path: Path, tex_path: Path) -> str:
    """Return the path to a ``.dat`` file relative to the ``.tex`` file."""
    return str(dat_path.relative_to(tex_path.parent))


def _band_plot(upper_path: str, lower_path: str) -> str:
    """Return the tikz commands for the grey ±1 std band using fill between."""
    return (
        f"\\addplot [name path=upper, draw=none] table {{{upper_path}}};\n"
        f"\\addplot [name path=lower, draw=none] table {{{lower_path}}};\n"
        "\\addplot [gray, fill=gray, opacity=0.4] fill between[of=upper and lower];"
    )


def _subplot_body(
    model: str,
    distribution_label: str,
    series_paths: dict[str, Path],
    tex_path: Path,
    n_bins: int,
    ymin: float,
    ymax: float,
    bias_adjusted: bool,
) -> str:
    """Return the tikz commands for a single \\nextgroupplot panel."""
    suffix = ", bias adjusted" if bias_adjusted else ""
    title = f"{model.upper()}, {distribution_label}{suffix}"

    upper = _rel(series_paths["band_upper"], tex_path)
    lower = _rel(series_paths["band_lower"], tex_path)
    mean_ = _rel(series_paths["mean"], tex_path)
    obs = _rel(series_paths["observed"], tex_path)

    lines = [
        "\\nextgroupplot[",
        "tick align=outside,",
        "tick pos=left,",
        f"title={{{title}}},",
        "x grid style={darkgray176},",
        f"xmin=0, xmax={n_bins},",
        "xtick style={color=black},",
        "y grid style={darkgray176},",
        f"ymin={ymin:.15g}, ymax={ymax:.15g},",
        "ytick style={color=black}",
        "]",
        _band_plot(upper, lower),
        f"\\addplot [thick, black] table {{{mean_}}};",
        "\\addplot [semithick, black, mark=*, mark size=1, mark options={solid}, only marks]",
        f"table {{{obs}}};",
    ]
    return "\n".join(lines)


def write_tikz(
    path: Path,
    models: list[str],
    distribution_label: str,
    dat_paths: dict[str, dict[str, dict[str, Path]]],
    n_bins: int,
    ymin: float,
    ymax: float,
    bias_adjustment: bool,
) -> None:
    """Write a pgfplots groupplot ``.tex`` file to *path*.

    Args:
        path: Destination ``.tex`` file.
        models: Ordered list of model names (one column per model).
        distribution_label: Human-readable distribution name for subplot titles.
        dat_paths: Nested dict ``dat_paths[model][variant][series]`` where
            *variant* is ``"unadjusted"`` or ``"adjusted"`` and *series* is
            one of ``"mean"``, ``"observed"``, ``"band_upper"``, ``"band_lower"``.
        n_bins: Number of bins (sets the x-axis range to ``[0, n_bins]``).
        ymin: Shared y-axis minimum across all panels.
        ymax: Shared y-axis maximum across all panels.
        bias_adjustment: Whether a second row of bias-adjusted panels is included.
    """
    n_cols = len(models)
    n_rows = 2 if bias_adjustment else 1

    subplots: list[str] = []

    # Top row: unadjusted
    for model in models:
        subplots.append(
            _subplot_body(
                model=model,
                distribution_label=distribution_label,
                series_paths=dat_paths[model]["unadjusted"],
                tex_path=path,
                n_bins=n_bins,
                ymin=ymin,
                ymax=ymax,
                bias_adjusted=False,
            )
        )

    # Bottom row: bias-adjusted
    if bias_adjustment:
        for model in models:
            subplots.append(
                _subplot_body(
                    model=model,
                    distribution_label=distribution_label,
                    series_paths=dat_paths[model]["adjusted"],
                    tex_path=path,
                    n_bins=n_bins,
                    ymin=ymin,
                    ymax=ymax,
                    bias_adjusted=True,
                )
            )

    body = "\n\n".join(subplots)

    tex = (
        "% Generated by numerical_illustration/plots/tikz_writer.py\n"
        "% Requires: pgfplots, pgfplotsthesis (fill between library)\n"
        "% Add to preamble: \\usepgfplotslibrary{fillbetween}\n"
        "\\begin{tikzpicture}[scale = 0.75]\n"
        "\n"
        "\\definecolor{darkgray176}{RGB}{176,176,176}\n"
        "\\definecolor{gray}{RGB}{128,128,128}\n"
        "\n"
        f"\\begin{{groupplot}}[group style={{group size={n_cols} by {n_rows}, "
        "vertical sep=1.5cm}]\n"
        f"{body}\n"
        "\\end{groupplot}\n"
        "\n"
        "\\end{tikzpicture}\n"
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(tex)
